
- name: Install Cinnamon Desktop Environment
  apt:
    state: latest
    name:
      - cinnamon-desktop-environment
      - cinnamon-screensaver
      - xscreensaver-data
      - xscreensaver-data-extra
      - xscreensaver-gl
      - xscreensaver-gl-extra

- name: Remove annoying logos from bootup
  copy:
    src: ubuntu-logo.png
    dest: /usr/share/plymouth/ubuntu-logo.png
    owner: root
    group: root
    mode: '0644'
